yahoo_music:
  hop: 3
  epochs: 200
  ensemble: True
  batch_size: 64
  max_neighbors: 50
  max_walks: 10
  lr_scheduler:
    - range_epoch: 0,120
      range_lr: 1e-3,1e-3
    - range_epoch: 120,160
      range_lr: 8.5e-4,8.5e-4
    - range_epoch: 160,200
      range_lr: 7e-4,7e-4

flixster:
  hop: 1
  epochs: 200
  batch_size: 64
  max_neighbors: 50
  max_walks: 10
  lr_scheduler:
    - range_epoch: 0,80
      range_lr: 1e-3,1e-3
    - range_epoch: 80,120
      range_lr: 8e-4,8e-4
    - range_epoch: 120,160
      range_lr: 6e-4,6e-4
    - range_epoch: 160,200
      range_lr: 4e-4,4e-4

douban:
  hop: 1
  epochs: 200
  batch_size: 64
  max_neighbors: 50
  max_walks: 10
  lr_scheduler:
    - range_epoch: 0,100
      range_lr: 1e-3,1e-3
    - range_epoch: 80,120
      range_lr: 8e-4,8e-4
    - range_epoch: 120,160
      range_lr: 6e-4,6e-4
    - range_epoch: 160,200
      range_lr: 4e-4,4e-4

ml_1m:
  save_appendix: _mnhp100
  data_appendix: _mnph100
  max_nodes_per_hop: 100
  epochs: 200
  batch_size: 64
  dynamic_train: True
  max_neighbors: 50
  max_walks: 10
  lr_scheduler:
    - range_epoch: 0,80
      range_lr: 1e-3,1e-3
    - range_epoch: 80,120
      range_lr: 8e-4,8e-4
    - range_epoch: 120,160
      range_lr: 6e-4,6e-4
    - range_epoch: 160,200
      range_lr: 4e-4,4e-4

ml_100k:
  save_appendix: _mnph200
  data_appendix: _mnph100
  max_nodes_per_hop: 200
  epochs: 200
  batch_size: 64
  dynamic_train: True
  max_neighbors: 50
  max_walks: 10
  lr_scheduler:
    - range_epoch: 0,80
      range_lr: 1e-3,1e-3
    - range_epoch: 80,120
      range_lr: 8e-4,8e-4
    - range_epoch: 120,160
      range_lr: 6e-4,6e-4
    - range_epoch: 160,200
      range_lr: 4e-4,4e-4
