yahoo_music:
  hop: 3
  epochs: 200
  testing: True
  ensemble: True
  lr: 3e-3
  batch_size: 64
  max_neighbors: 50
  max_walks: 10

flixster:
  hop: 1
  epochs: 200
  testing: True
  ensemble: True
  lr: 3e-3
  batch_size: 64
  max_neighbors: 50
  max_walks: 10

douban:
  hop: 1
  epochs: 200
  testing: True
  ensemble: True
  lr: 3e-3
  batch_size: 128
  max_neighbors: 50
  max_walks: 10

ml_1m:
  save_appendix: _mnhp100
  data_appendix: _mnph100
  max_nodes_per_hop: 100
  testing: True
  epochs: 200
  save_interval: 5
  lr_decay_step_size: 20
  lr: 3e-3
  batch_size: 64
  ensemble: True
  dynamic_train: True
  max_neighbors: 50
  max_walks: 10

ml_100k:
  save_appendix: _mnph200
  data_appendix: _mnph100
  max_nodes_per_hop: 200
  testing: True
  epochs: 200
  save_interval: 5
  lr_decay_step_size: 20
  lr: 3e-3
  batch_size: 64
  ensemble: True
  dynamic_train: True
  max_neighbors: 50
  max_walks: 10
