yahoo_music:
  hop: 3
  epochs: 100
  testing: True
  ensemble: True
  # continue_from: 40
  lr: 8e-3
  batch_size: 64
  max_neighbors: 50
  max_walks: 10
  percent_warmup: 0.2
  init_lr: 5e-4

flixster:
  hop: 1
  epochs: 100
  testing: True
  ensemble: True
  # continue_from: 40
  lr: 8e-3
  batch_size: 64
  max_neighbors: 50
  max_walks: 10
  percent_warmup: 0.2
  init_lr: 5e-4

douban:
  hop: 1
  epochs: 100
  testing: True
  ensemble: True
  # continue_from: 40
  lr: 8e-3
  batch_size: 64
  max_neighbors: 50
  max_walks: 10
  percent_warmup: 0.2
  init_lr: 5e-4

ml_1m:
  save_appendix: _mnhp100
  data_appendix: _mnph100
  max_nodes_per_hop: 100
  testing: True
  epochs: 100
  save_interval: 5
  lr_decay_step_size: 20
  lr: 8e-3
  batch_size: 64
  ensemble: True
  dynamic_train: True
  max_neighbors: 50
  max_walks: 10
  percent_warmup: 0.2
  init_lr: 5e-4

ml_100k:
  save_appendix: _mnph200
  data_appendix: _mnph100
  max_nodes_per_hop: 200
  testing: True
  epochs: 100
  save_interval: 5
  lr_decay_step_size: 20
  lr: 8e-3
  batch_size: 64
  ensemble: True
  dynamic_train: True
  max_neighbors: 50
  max_walks: 10
  percent_warmup: 0.2
  init_lr: 5e-4
